### ISSUE TITLE
Colors missing + error message

### ISSUE THREAD

**Issue by simonced** [I3ck/ThemeBow#1]
Hi,

ThemeBow is a great initiative, I suppose that the theme files are dynamically generated, but I found some issues.

When activating a colorscheme, I have that error:

> Error detected while processing oranges-vim-themebow.vim:
> line   50:
> E254: Cannot allocate color #

Vim version: `7.4` with patches _802_ 64bit on Windows 8.1

Also, quite a lot of colors are not set correctly like the current line color, gutter, context menu etc...

**Comment by I3ck** [comment]
The parsing bug should be fixed now, thanks for notifying me

**Comment by I3ck** [comment]
Many more colors should work aswell, since the file was broken from line50 onwards. But I'll take a closer look

**Comment by I3ck** [comment]
The diversity of colors within the vim template should now be greatly improved
(some themes only supply very few colors, tho)
Just let me know where colors are missing

**Comment by I3ck** [comment]
there's still some issues I have to figure out

**Comment by simonced** [comment]
Thank you for the updates.
An error on line 63 in the theme `oranges` for example. It might be what you spotted already.

I let you tell me when I can test further ;)

**Comment by I3ck** [comment]
Fixed.  
I just noticed that the themes only work for gvim or at least terminals which support all the colors
I'll open an issue for that and close this one
Thank you for your feedback and enjoy the themes in gvim :)

**Comment by simonced** [comment]
Hi,

The errors are gone now.

But I noticed (for the oranges theme I tried) that we can't see our cursor nor the active line number (too bright). The cursorline is also invisible.

I use Gvim.
